### ISSUE TITLE
java.lang.ClassCastException: class com.wonderfulenchantments.enchantments.MithridatismEnchantment$MithridatismProtectionEffect cannot be cast to class net.minecraft.world.item.alchemy.Potion (Initializing game)

### ISSUE THREAD

**Issue by Coraline77447** [Majrusz/MinecraftMods#37]
Something's wrong with the Mithridatism enchantment during the Initializing game phase.
Has to do with Mithridatism's protection effect within it's coding?
Minecraft: 1.17.1
Forge: 37.0.25
WonderfulEnchantments: 1.4.0
Optifine Installed?: No, not compatible with forge 1.17 yet.
Crash Report: https://pastebin.com/ig9eW93B
Log: [latest.log](https://github.com/Majrusz/WonderfulEnchantmentsMod/files/6931343/latest.log)

Btw I'm not good with naming crash reports or issue reports when something like this happens... 
So that's why the name is ridiculously long since the name of this report is pretty much where the issue resides in.

**Comment by Majrusz** [comment]
Fixed, check out the new 1.4.1 version and thanks! :)

**Comment by Coraline77447** [comment]
Alright, I'll try it out tomorrow since today's play session is gonna be in 1.16.5 cause at the moment modded 1.17 ain't like modded 1.16 without A.O.A (Advent of Ascension aka Nevermine) and other fun mods that haven't been ported over yet.
I may have already gotten bored/burned out of modded 1.17 so I'm gonna balance it with my modded 1.16.5 world(s) to make the current modded 1.17.1 world that I have relevant and fun still until the other mods both big and small gets ported over to 1.17 like A.O.A for an example.

So today is my modded 1.16.5 world called Coraline World 3: A.O.A.
Tomorrow will be my modded 1.17.1 world called Coraline World 1.17.1 (Modded).

**Comment by Coraline77447** [comment]
I'm back with important and unfortunate news, the game is still crashing with Wonderful Enchamtnemts...
This time with an unknown error but the game is crashing during early mod loading.
The forge devs may have changed something that's causing the mod to fail during mod loading, also from 37.0.20+ they removed some old methods and some were removal methods like boolean for an example which it no longer exists.
So maybe you should go check your mod's methods and whatnot and remove non-existing methods that were removed from forge and maybe the mod could work again in 1.17+ versions.
